### ISSUE TITLE
Can't load data when using dask's distributed client

### ISSUE THREAD

**Issue by aulemahal** [neishm/fstd2nc#82]
Hi! Thanks for the useful package!

It seems that I can't use a dask distributed Client when reading FST files. For the example, I took a file from the SPS toy datasets.

```python3
import xarray
from dask.distributed import Client

if __name__ == '__main__':
    c = Client(dashboard_address=8889, n_workers=4, threads_per_worker=4, memory_limit='9GB')

    ds = xr.open_dataset('sps_dbase/jouet_isba/ana_20151005_006')
    ds.load()  # "Loads" the data into dask datasets
    ds.load()  # Actually load the data into memory
```
Fails with many instances of :
```
distributed.scheduler - ERROR - Composite key contains unexpected key type at index=1 (key=('I7-46d8a287ccb916154fa82039308afe6', 0, 0, 0, 0))
```

See the full log:

<details>

```
2024-03-14 13:44:06,939 - distributed.scheduler - ERROR - Composite key contains unexpected key type at index=1 (key=('I7-d46d8a287ccb916154fa82039308afe6', 0, 0, 0, 0))
Traceback (most recent call last):
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/core.py", line 235, in validate_key
    validate_key(part)
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/core.py", line 240, in validate_key
    raise TypeError(f"Unexpected key type {typ} ({key=!r})")
TypeError: Unexpected key type <class 'numpy.int64'> (key=0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/utils.py", line 832, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/scheduler.py", line 4697, in update_graph
    ) = await offload(
        ^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/utils.py", line 1540, in run_in_executor_with_context
    return await loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/utils.py", line 1541, in <lambda>
    executor, lambda: context.run(func, *args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/scheduler.py", line 8879, in _materialize_graph
    validate_key(k)
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/core.py", line 237, in validate_key
    raise TypeError(
TypeError: Composite key contains unexpected key type at index=1 (key=('I7-d46d8a287ccb916154fa82039308afe6', 0, 0, 0, 0))
2024-03-14 13:44:06,953 - distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/core.py", line 235, in validate_key
    validate_key(part)
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/core.py", line 240, in validate_key
    raise TypeError(f"Unexpected key type {typ} ({key=!r})")
TypeError: Unexpected key type <class 'numpy.int64'> (key=0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/core.py", line 970, in _handle_comm
    result = await result
             ^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/scheduler.py", line 5711, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/core.py", line 1051, in handle_stream
    await handler(**merge(extra, msg))
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/utils.py", line 832, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/scheduler.py", line 4697, in update_graph
    ) = await offload(
        ^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/utils.py", line 1540, in run_in_executor_with_context
    return await loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/utils.py", line 1541, in <lambda>
    executor, lambda: context.run(func, *args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/scheduler.py", line 8879, in _materialize_graph
    validate_key(k)
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/core.py", line 237, in validate_key
    raise TypeError(
TypeError: Composite key contains unexpected key type at index=1 (key=('I7-d46d8a287ccb916154fa82039308afe6', 0, 0, 0, 0))
Task exception was never retrieved
future: <Task finished name='Task-1017' coro=<Server._handle_comm() done, defined at /exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/core.py:876> exception=TypeError("Composite key contains unexpected key type at index=1 (key=('I7-d46d8a287ccb916154fa82039308afe6', 0, 0, 0, 0))")>
Traceback (most recent call last):
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/core.py", line 235, in validate_key
    validate_key(part)
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/core.py", line 240, in validate_key
    raise TypeError(f"Unexpected key type {typ} ({key=!r})")
TypeError: Unexpected key type <class 'numpy.int64'> (key=0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/core.py", line 970, in _handle_comm
    result = await result
             ^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/scheduler.py", line 5711, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/core.py", line 1051, in handle_stream
    await handler(**merge(extra, msg))
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/utils.py", line 832, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/scheduler.py", line 4697, in update_graph
    ) = await offload(
        ^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/utils.py", line 1540, in run_in_executor_with_context
    return await loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/utils.py", line 1541, in <lambda>
    executor, lambda: context.run(func, *args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/scheduler.py", line 8879, in _materialize_graph
    validate_key(k)
  File "/exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/core.py", line 237, in validate_key
    raise TypeError(
TypeError: Composite key contains unexpected key type at index=1 (key=('I7-d46d8a287ccb916154fa82039308afe6', 0, 0, 0, 0))
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
Cell In[13], line 1
----> 1 ds.load().load()

File /exec/prod2/.conda/sps/lib/python3.11/site-packages/xarray/core/dataset.py:845, in Dataset.load(self, **kwargs)
    842 chunkmanager = get_chunked_array_type(*lazy_data.values())
    844 # evaluate all the chunked arrays simultaneously
--> 845 evaluated_data: tuple[np.ndarray[Any, Any], ...] = chunkmanager.compute(
    846     *lazy_data.values(), **kwargs
    847 )
    849 for k, data in zip(lazy_data, evaluated_data):
    850     self.variables[k].data = data

File /exec/prod2/.conda/sps/lib/python3.11/site-packages/xarray/namedarray/daskmanager.py:86, in DaskManager.compute(self, *data, **kwargs)
     81 def compute(
     82     self, *data: Any, **kwargs: Any
     83 ) -> tuple[np.ndarray[Any, _DType_co], ...]:
     84     from dask.array import compute
---> 86     return compute(*data, **kwargs)

File /exec/prod2/.conda/sps/lib/python3.11/site-packages/dask/base.py:661, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    658     postcomputes.append(x.__dask_postcompute__())
    660 with shorten_traceback():
--> 661     results = schedule(dsk, keys, **kwargs)
    663 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File /exec/prod2/.conda/sps/lib/python3.11/site-packages/distributed/client.py:2233, in Client._gather(self, futures, errors, direct, local_worker)
   2231     else:
   2232         raise exception.with_traceback(traceback)
-> 2233     raise exc
   2234 if errors == "skip":
   2235     bad_keys.add(key)

CancelledError: ('DN-d46d8a287ccb916154fa82039308afe6', 0, 0, 0)
```

</details>

I don't know `fstd2nc` good enough yet, but it feels like the issue stems from `fstd2nc.mixins.extern._iter_dask`. Precisely, the issue is that the indexes in the key are `np.int64` objects. And dask's function does not recognize it as an int. Example:
```python3
import numpy as np

isinstance(np.int64(2), int)  # False
```
(This feels quite unpythonic from `dask` and `numpy`, where's the famous "duck typing" ?)

I guess the best solution would be to ensure the integers passed into the keys are explicitly casted with `int` ?

Not sure also why this issue isn't raised when the local scheduler is used instead...

**Comment by neishm** [comment]
Hi @aulemahal, thanks for the bug report!  I don't use distributed myself, so hadn't encountered this particular problem before.  I just pushed an update to the development branch that hopefully puts the key into the right integer type.

Are you able to test by installing directly from the dev branch of the repository?  E.g.,
```
pip install git+https://github.com/neishm/fstd2nc.git@dev
```

**Comment by aulemahal** [comment]
Yes the dev branch fixes my problem! Thanks!
