### ISSUE TITLE
conversion error: internal pb with the script

### ISSUE THREAD

**Issue by guziy** [neishm/fstd2nc#94]
The input file seems to be the legacy fst but, I think, the converter treats it as rsf..

```
r.filetype /fs/site6/eccc/cmd/e/olh001/maestro/gesps/gesps_surge_prog_component/hub/work/20241006120000/main/loop_ensemble/surge_prog/forcings_compute/to_cdf+1+TM/input/INP_DIR/2024100612_w_temp_eorca12_H192

#=> File type is RPN standard random 98
```

I tried 2 most recent versions of the converter, but getting the following error...

```bash
++ /fs/site6/eccc/cmd/e/olh001/maestro/gesps/gesps_surge_prog_component/hub/work/20241006120000/main/loop_ensemble/surge_prog/forcings_compute/to_cdf+1+TM/bin/fstd2nc --vars TM --exclude depth,height,leadtime,reftime --ignore-etiket /fs/site6/eccc/cmd/e/olh001/maestro/gesps/gesps_surge_prog_component/hub/work/20241006120000/main/loop_ensemble/surge_prog/forcings_compute/to_cdf+1+TM/input/INP_DIR/2024100612_w_temp_eorca12_H096 /fs/site6/eccc/cmd/e/olh001/maestro/gesps/gesps_surge_prog_component/hub/work/20241006120000/main/loop_ensemble/surge_prog/forcings_compute/to_cdf+1+TM/input/INP_DIR/2024100612_w_temp_eorca12_H192 /fs/site6/eccc/cmd/e/olh001/maestro/gesps/gesps_surge_prog_component/hub/work/20241006120000/main/loop_ensemble/surge_prog/forcings_compute/to_cdf+1+TM/input/INP_DIR/2024100612_w_temp_eorca12_H288 /fs/site6/eccc/cmd/e/olh001/maestro/gesps/gesps_surge_prog_component/hub/work/20241006120000/main/loop_ensemble/surge_prog/forcings_compute/to_cdf+1+TM/input/INP_DIR/2024100612_w_temp_eorca12_H384 /fs/site6/eccc/cmd/e/olh001/maestro/gesps/gesps_surge_prog_component/hub/work/20241006120000/main/loop_ensemble/surge_prog/forcings_compute/to_cdf+1+TM/output/OUT_DIR_BEFORE_SPLIT/2024100612_TM.nc
Found 4 RPN standard file(s)
Warning: Raw binary records detected.  The values may not be properly decoded
    if you're opening on a different platform.
Will look for variables: TM
Warning: Internal problem with the script - unable to get data for 'TM'
Traceback (most recent call last):
  File "/fs/site6/eccc/cmd/e/olh001/maestro/gesps/gesps_surge_prog_component/hub/work/20241006120000/main/loop_ensemble/surge_prog/forcings_compute/to_cdf+1+TM/bin/fstd2nc", line 11, in <module>
    load_entry_point('fstd2nc==0.20240401.2', 'console_scripts', 'fstd2nc')()
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20240401.2/all/lib/python/fstd2nc/__main__.py", line 237, in _fstd2nc_cmdline_trapped
    _fstd2nc_cmdline (*args, **kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20240401.2/all/lib/python/fstd2nc/__main__.py", line 230, in _fstd2nc_cmdline
    buf.to_netcdf(outfile, nc_format=nc_format, global_metadata=global_metadata, zlib=zlib, compression=compression, progress=progress, turbo=turbo)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20240401.2/all/lib/python/fstd2nc/mixins/netcdf.py", line 468, in to_netcdf
    data = self._read_record (r)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20240401.2/all/lib/python/fstd2nc/mixins/__init__.py", line 1115, in _read_record
    data = self._decode(np.fromfile(f,'B',length))
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20240401.2/all/lib/python/fstd2nc/mixins/fstd.py", line 192, in _decode
    meta, _, _ = _split_meta(data[:100])
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20240401.2/all/lib/python/fstd2nc/extra.py", line 67, in _split_meta
    raise Exception  # Unknown endian / bad data?
Exception

```

**Comment by guziy** [comment]
For `0.20231105.2` version I get a different error:

```bash
Warning: Internal problem with the script - unable to get data for 'TM'
Traceback (most recent call last):
  File "/fs/ssm/eccc/mrd/rpn/MIG/ENV/d/rpnpy/2.2.0/lib/rpnpy/librmn/fstd98.py", line 126, in dtype_fst2numpy
    return _rc.FST_DATYP2NUMPY_LIST[datyp]
KeyError: 34

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fs/site6/eccc/cmd/e/olh001/maestro/gesps/gesps_surge_prog_component/hub/work/20241006120000/main/loop_ensemble/surge_prog/forcings_compute/to_cdf+1+TM/bin/fstd2nc", line 11, in <module>
    load_entry_point('fstd2nc==0.20231105.2', 'console_scripts', 'fstd2nc')()
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20231105.2/all/lib/python/fstd2nc/__main__.py", line 237, in _fstd2nc_cmdline_trapped
    _fstd2nc_cmdline (*args, **kwargs)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20231105.2/all/lib/python/fstd2nc/__main__.py", line 230, in _fstd2nc_cmdline
    buf.to_netcdf(outfile, nc_format=nc_format, global_metadata=global_metadata, zlib=zlib, compression=compression, progress=progress, turbo=turbo)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20231105.2/all/lib/python/fstd2nc/mixins/netcdf.py", line 468, in to_netcdf
    data = self._read_record (r)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20231105.2/all/lib/python/fstd2nc/mixins/__init__.py", line 1115, in _read_record
    data = self._decode(np.fromfile(f,'B',length))
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20231105.2/all/lib/python/fstd2nc/mixins/fstd.py", line 189, in _decode
    dtype = dtype_fst2numpy(datyp, nbits)
  File "/fs/ssm/eccc/crd/ccmr/EC-CAS/fstd2nc/0.20231105.2/all/lib/python/fstd2nc/mixins/fstd.py", line 41, in dtype_fst2numpy
    return dtype_fst2numpy(datyp,nbits)
  File "/fs/ssm/eccc/mrd/rpn/MIG/ENV/d/rpnpy/2.2.0/lib/rpnpy/librmn/fstd98.py", line 128, in dtype_fst2numpy
    raise FSTDError('', e)
rpnpy.librmn.fstd98.FSTDError: ('', KeyError(34,))
```

**Comment by neishm** [comment]
Thanks for the bug report.  Able to reproduce the message on my end with those files, but still trying to determine the source of the problem.  My initial hunch is it may have something to do with how it's pairing the records with the corresponding mask fields.  If I short-circuit the masking code then it no longer crashes, but I don't why...

**Comment by neishm** [comment]
Ok, I think I understand the issue that's going on.

First, there's some overlap between the files (end time step from one file is repeated at the beginning of the next file).  That's perfect valid, but it is confusing some later steps in the converter.
When it's pairing up the 'P@' and '@@' records, it may be randomly picking each component from a different file where the records are repeated in the next file.  In later parts of the code where it's fetching the data, it assumes the '@@' record is in the same file as the 'P@' record.  If that's not the case, it may be trying to read data from the right place but the wrong file, resulting in garbage for the mask.

I'm going to try refining the mask logic to make sure it's pairing within the same file, and see if that resolves the issue.

**Comment by neishm** [comment]
Hi @guziy, can you test with the following package on the science network and see if it helps?
```
. ssmuse-sh -p /fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20240625.5-rc1
```
If that resolves the issue, I'll publish it as a new version.

**Comment by guziy** [comment]
Thanks Michael:

I will test this version. 

Actually, fstd2nc failing allowed me to realize that there are duplicates and helped us fix a bug (make some improvements) in our code.

**Comment by guziy** [comment]
Thanks Michael:

the new version works (`/fs/ssm/eccc/crd/ccmr/EC-CAS/master/fstd2nc_0.20240625.5-rc1_all`)`

It seems like something has changed with 3d fields, some downstream tasks fail with the old converter and work ok with the new one (I'll try to figure this one out).

**Comment by neishm** [comment]
Ok, I've pushed a new version 0.20240625.5 with the fix.

Would it be alright to grab a copy of those input files, to add to the test suite on the science network?  The problem seems fixed for now, but want to make sure it doesn't regress in future code updates.

**Comment by guziy** [comment]
sure Michael, it is ok to take the temporary files. Thanks a lot for your prompt reaction!
